"""Pins for the codegen-from-business-rule + round-trip understanding probe.

These lock two claims from docs/codegen_understand.md:

  1. CODEGEN is compositional — a terse business rule ("compute accrual") is expanded by RECURSIVE
     subgoal expansion into real Python, written bottom-to-top, trusted only because it re-executes
     to `principal*rate*days/365`. The headline is the *readability flip*: adding `readable` requires
     `named_steps`, which excludes the compact inline decomposition (mirror of spec_synthesis's
     strictness flip, now over whole DECOMPOSITIONS, not single statements).

  2. UNDERSTANDING is synthesis backwards — recognize code the system itself generated (attribute the
     function node "computes accrual"); when a function was NOT generated by us, recognition derives
     nothing, so a fact is SUPPLIED in CNL (`mystery is_a sort_function`), no derivation.

See experiments/codegen_understand.py for the design narrative.
"""
import ast

import pytest

from ugm import load_machine_rules, ask_goal

from experiments.codegen_understand import (
    Spec, PLANS, RECIPES, PARAMS, RULES, _planning_graph,
    retrieve, is_complete, realize_trace, choose_plan, emit, _topo,
    verify_computes_accrual, synthesize, recognize, supply_fact_graph, _expected,
)


@pytest.fixture
def lenient():
    return Spec(name="accrual_spec", intent="accrual", fn_name="compute_accrual")


@pytest.fixture
def readable():
    return Spec(name="accrual_spec", intent="accrual", fn_name="compute_accrual", readable=True)


def test_recursive_expansion_bottoms_out_at_params(lenient):
    """COMPLETENESS: both decompositions are complete — every sub-need is either produced by a
    recipe in the plan or is a leaf parameter. This is the recursive subgoal expansion, checked as
    stratified Datalog (a plan with an unproduced non-param need would have a gap)."""
    assert is_complete(lenient, "plan_inline")
    assert is_complete(lenient, "plan_stepwise")


def test_a_gap_makes_a_plan_incomplete(lenient):
    """The dual: a need that is neither a param nor produced in the plan is a GAP, so `complete`
    is not derived. Pins that completeness genuinely checks the whole subgoal tree, not just the root."""
    rules = load_machine_rules(RULES)
    g = _planning_graph(lenient)
    # inject a broken plan whose root needs an unsatisfiable sub-need `mystery_need`.
    # cache nodes by name — add_node mints a FRESH node each call, which would split a subject
    # across duplicate nodes and break the join.
    ids: dict[str, str] = {}
    def node(x: str) -> str:
        if x not in ids: ids[x] = g.add_node(x)
        return ids[x]
    for s, p, o in [("plan_broken", "is_a", "plan"), ("plan_broken", "for_intent", "accrual"),
                    ("r_broken", "in_plan", "plan_broken"), ("r_broken", "produces", "accrual"),
                    ("r_broken", "needs", "mystery_need")]:
        g.add_relation(node(s), p, node(o))
    assert ask_goal(g, "is plan_broken has_gap yes", rules) == ["yes"]
    assert ask_goal(g, "is plan_broken complete yes", rules) != ["yes"]


def test_lenient_retrieval_and_choose(lenient):
    """Both complete plans realize a lenient spec; CHOOSE grades by compactness, so the one-statement
    inline decomposition wins (the stepwise loser is retained in the trace, not discarded)."""
    assert sorted(p.name for p in retrieve(lenient)) == ["plan_inline", "plan_stepwise"]
    winner, trace = choose_plan(retrieve(lenient))
    assert winner.name == "plan_inline"
    assert any("plan_stepwise" in line for line in trace)


def test_readable_flip_excludes_the_inline_plan(readable):
    """The headline: requiring `readable` (=> `named_steps`), ONLY the stepwise decomposition
    realizes — the compact inline plan is excluded because it MISSES that feature. An added
    requirement flips the winner away from compactness."""
    assert sorted(p.name for p in retrieve(readable)) == ["plan_stepwise"]
    winner, _ = choose_plan(retrieve(readable))
    assert winner.name == "plan_stepwise"


def test_readable_exclusion_is_a_derived_miss(readable):
    """WHY inline is excluded is rule-derived: under `readable`, `plan_inline` MISSES the spec
    because it LACKS `named_steps` (stratified negation). The stepwise plan provides it, so misses not."""
    rules = load_machine_rules(RULES)
    g = _planning_graph(readable)
    assert ask_goal(g, "is plan_inline misses accrual_spec", rules) == ["yes"]
    assert ask_goal(g, "is plan_inline lacks named_steps", rules) == ["yes"]
    assert ask_goal(g, "is plan_stepwise misses accrual_spec", rules) != ["yes"]


def test_code_is_written_bottom_to_top(readable):
    """EMIT: the stepwise decomposition is written leaves-first — `annual_interest` and
    `day_fraction` bind BEFORE the `accrual` that reads them; the return is last. This is the doc's
    'code is written bottom to top' via topological order over the subgoal DAG."""
    order = [r.produces for r in _topo(PLANS[1])]      # plan_stepwise
    assert order.index("accrual") == len(order) - 1
    assert order.index("annual_interest") < order.index("accrual")
    assert order.index("day_fraction") < order.index("accrual")
    src = emit(readable, PLANS[1])
    assert src.strip() == (
        "def compute_accrual(principal, rate, days):\n"
        "    annual_interest = principal * rate\n"
        "    day_fraction = days / 365\n"
        "    accrual = annual_interest * day_fraction\n"
        "    return accrual"
    )


def test_inline_emits_one_statement(lenient):
    """The compact winner is a single-statement decomposition straight from the leaf parameters."""
    src = emit(lenient, PLANS[0])
    assert src.strip() == (
        "def compute_accrual(principal, rate, days):\n"
        "    accrual = principal * rate * days / 365\n"
        "    return accrual"
    )


def test_both_decompositions_verify_by_execution(lenient, readable):
    """TRUST BY EXECUTION: both emitted forms are RUN and must compute the accrual formula. Two
    different decompositions, one behaviour — the generator is believed only because it re-executes."""
    assert verify_computes_accrual(emit(lenient, PLANS[0]), lenient.fn_name)
    assert verify_computes_accrual(emit(readable, PLANS[1]), readable.fn_name)


def test_verification_catches_a_wrong_recipe(lenient):
    """The check has teeth: a decomposition that divides by the wrong constant fails the concrete
    check — so a mis-built recipe cannot pass as correct just by being retrieved."""
    src = ("def compute_accrual(principal, rate, days):\n"
           "    accrual = principal * rate * days / 360\n"   # wrong day-count basis
           "    return accrual")
    assert verify_computes_accrual(src, "compute_accrual") is False
    assert abs(_expected(1000.0, 0.05, 30.0) - 1000.0 * 0.05 * 30.0 / 365) < 1e-9


def test_synthesize_end_to_end(lenient, readable):
    """The whole loop: retrieve -> choose -> emit -> verify, for both specs. Lenient picks inline,
    readable flips to stepwise, both hold under execution."""
    r_lenient = synthesize(lenient)
    assert r_lenient.winner == "plan_inline" and r_lenient.computes_ok
    r_readable = synthesize(readable)
    assert r_readable.winner == "plan_stepwise" and r_readable.computes_ok


def test_rationale_trace_threads_completeness(readable):
    """RECORD: the realize-trace is genuine ugm provenance and threads the COMPLETENESS derivation
    (the recursive expansion) under the realizes head — the spec->code mirror of the exec trace."""
    text = "\n".join(realize_trace(readable, "plan_stepwise"))
    assert "plan_stepwise realizes accrual_spec" in text and "<- rule" in text
    assert "plan_stepwise complete yes" in text
    assert "accrual_spec intent accrual" in text


def test_round_trip_recognition(readable):
    """UNDERSTANDING: recognize code the system itself generated — attaching the winning plan's
    topology to the emitted function derives `compute_accrual computes accrual`, bridging the
    business term to the code (synthesis backwards, over the SAME completeness derivation)."""
    assert recognize(readable, "plan_stepwise", "compute_accrual") == \
        ["compute_accrual computes accrual"]


def test_unrecognized_code_falls_back_to_a_supplied_cnl_fact():
    """The escape hatch: a function we did NOT generate has no plan fingerprint, so recognition
    derives nothing — the fact is SUPPLIED directly in CNL (`mystery is_a sort_function`), answered
    with no derivation. This is the doc's 'provide a fact without relying on fact derivation'."""
    rules = load_machine_rules(RULES)
    # nothing computes accrual in a graph with no emitted-plan fingerprint
    assert ask_goal(_planning_graph(Spec("s", "accrual", "f")), "who computes accrual", rules) \
        == ["(no answer)"]
    # but the directly-authored fact is available immediately, exactly like a derived one
    assert ask_goal(supply_fact_graph(), "who is_a sort_function", rules) \
        == ["mystery is_a sort_function"]


def test_recipe_pool_is_bounded_and_real(lenient):
    """The emit tool pre-mints a BOUNDED recipe pool (rules select, never mint) — the compositional
    mirror of intake pre-minting the state lattice. Every recipe builds real Python; the pool size
    is the synthesis fuel budget."""
    assert set(PARAMS) == {"principal", "rate", "days"}
    for plan in PLANS:
        src = emit(lenient, plan)
        ast.parse(src)                                  # every decomposition is real Python
        for rname in plan.recipes:
            assert rname in RECIPES
